describe('Personnel -> Employees -> Profile Details Contact Info', () => {
    beforeEach(() => {
     cy.log('Login')
     cy.get('#Username').type('Richard')
     cy.get('#Password').type('Test123')
     cy.get('#Login').click()   
     // An employee is created having at least 2 addresses added.
     cy.get('#tree-item-4 > .k-link').click()
     cy.get('#tree-item-4_0 > .k-link').click().wait(3000)
     cy.get('.svx-grid-footer-buttons > .svx-button > .telerik-blazor').click()
     cy.get('.svx-block-body > :nth-child(2) > .svx-formfield-content > .input-group > .k-textbox').find('.k-input-inner').type('DeleteAddress')
     cy.get(':nth-child(7) > .svx-formfield-content > .k-combobox').find('.k-input-inner').click().type('OU 1').wait(5000).type('{enter}')
     cy.get(':nth-child(9) > .svx-formfield-content > .k-combobox').find('.k-input-inner').click().type('Status 1').wait(5000).type('{enter}')
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').wait(3000).click().wait(5000)
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').click()
     cy.get(':nth-child(3) > details > summary > .k-icon').click()
     cy.get(':nth-child(3) > details > .svx-panelbar-item-footer > .svx-button > .k-button').click()
     cy.get(':nth-child(1) > .svx-formfield-content > .k-combobox').find('.k-input-inner').type('Work').wait(3000).type('{enter}')
     cy.get('.svx-panelbar-type-section > :nth-child(2) > .svx-formfield-content > .input-group > .k-textbox').find('.k-input-inner').type('AddAddress1')
     cy.get('.svx-panelbar-type-section > :nth-child(3) > .svx-formfield-content > .input-group > .k-textbox').find('.k-input-inner').type('AddAddress2')
     cy.get('.svx-panelbar-type-section > :nth-child(4) > .svx-formfield-content > .input-group > .k-textbox').find('.k-input-inner').type('AddAddress3')
     cy.get(':nth-child(5) > .svx-formfield-content > .k-combobox').find('.k-input-inner').type('Brazil').wait(5000).type('{enter}')
     cy.get(':nth-child(6) > .svx-formfield-content > .k-combobox').find('.k-input-inner').type('Abu Dhabi').wait(5000).type('{enter}')
     cy.get(':nth-child(3) > details > .svx-panelbar-item-footer > .svx-button > .k-button').click()
     cy.get(':nth-child(2) > .svx-panelbar-type-section > :nth-child(1) > .svx-formfield-content > .k-combobox').find('.k-input-inner').type('Work').wait(3000).type('{enter}')
     cy.get(':nth-child(2) > .svx-panelbar-type-section > :nth-child(2) > .svx-formfield-content > .input-group > .k-textbox').find('.k-input-inner').type('Address11')
     cy.get(':nth-child(2) > .svx-panelbar-type-section > :nth-child(3) > .svx-formfield-content > .input-group > .k-textbox').find('.k-input-inner').type('Address22')
     cy.get(':nth-child(2) > .svx-panelbar-type-section > :nth-child(4) > .svx-formfield-content > .input-group > .k-textbox').find('.k-input-inner').type('Address33')
     cy.get(':nth-child(2) > .svx-panelbar-type-section > :nth-child(5) > .svx-formfield-content > .k-combobox').find('.k-input-inner').type('Bermuda').wait(5000).type('{enter}')
     cy.get(':nth-child(2) > .svx-panelbar-type-section > :nth-child(6) > .svx-formfield-content > .k-combobox').find('.k-input-inner').type('Abeche').wait(5000).type('{enter}')
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').wait(2000).click()
    })
    
it('Addresses -> Delete Address(es)', () => { 
cy.log('1. Expand Address(es) section and observe')
     cy.get('#tree-item-4_0 > .k-link').click().wait(3000)
     cy.get('[data-col-index="1"] > .k-filtercell > .k-filtercell-wrapper > .k-textbox').find('.k-input-inner').type('DeleteAddress').wait(5000)
     cy.get('.k-master-row > [data-col-index="1"]').dblclick()
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').click()
     cy.get(':nth-child(3) > details > summary > .k-icon').click()
     cy.get(':nth-child(1) > .svx-panelbar-item-delete-field > .svx-button > .k-button').should('exist')
     cy.get(':nth-child(2) > .svx-panelbar-item-delete-field > .svx-button > .k-button').should('exist')

cy.log('2. Click on the bin icon of the first address')
     cy.get(':nth-child(1) > .svx-panelbar-item-delete-field > .svx-button > .k-button').click()
     cy.get(':nth-child(2) > .svx-panelbar-item-delete-field > .svx-button > .k-button').should('not.exist')

cy.log('3. Click CANCEL') 
     cy.get('.modal-buttons > :nth-child(1) > .telerik-blazor').click().wait(3000)
     cy.get('.svx-column-block-right > .svx-block > .svx-block-body > :nth-child(3) > .k-card > .k-card-body').contains('AddAddress1, AddAddress2, AddAddress3 - Work')
     cy.get('.svx-column-block-right > .svx-block > .svx-block-body > :nth-child(3) > .k-card > .k-card-body').contains('Address11, Address22, Address33 - Work')

cy.log('4. Expand the Address(es) section, click on the bin icon of the first address and click SAVE')
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').click().wait(3000)
     cy.get(':nth-child(3) > details > summary > .k-icon').click().wait(3000)
     cy.get(':nth-child(1) > .svx-panelbar-item-delete-field > .svx-button > .k-button').click()
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').wait(2000).click()
     cy.get('.svx-column-block-right > .svx-block > .svx-block-body > :nth-child(3) > .k-card > .k-card-body').should('not.contain', 'AddAddress1, AddAddress2, AddAddress3 - Work')

cy.log('cleanup')
     cy.get('#tree-item-4_0 > .k-link').click().wait(3000)
     cy.get('[data-col-index="1"] > .k-filtercell > .k-filtercell-wrapper > .k-textbox').find('.k-input-inner').type('DeleteAddress').wait(5000)
     cy.get('.k-master-row > [data-col-index="0"] > .k-button > .telerik-blazor').click()
     cy.get('.k-button-solid-primary').click()
    })  
    })