describe('Personnel -> Employees -> Profile Details Contact Info', () => {
    beforeEach(() => {
     cy.log('Login')
     cy.get('#Username').type('Richard')
     cy.get('#Password').type('Test123')
     cy.get('#Login').click()   
     // An employee is created having at least 2 addresses added.
     cy.get('#tree-item-4 > .k-link').click()
     cy.get('#tree-item-4_0 > .k-link').click().wait(3000)
     cy.get('.svx-grid-footer-buttons > .svx-button > .telerik-blazor').click()
     cy.get('.svx-block-body > :nth-child(2) > .svx-formfield-content > .input-group > .k-textbox').find('.k-input-inner').type('EditAddress')
     cy.get(':nth-child(7) > .svx-formfield-content > .k-combobox').find('.k-input-inner').click().type('OU 1').wait(5000).type('{enter}')
     cy.get(':nth-child(9) > .svx-formfield-content > .k-combobox').find('.k-input-inner').click().type('Status 1').wait(5000).type('{enter}')
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').wait(3000).click().wait(5000)
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').click()
     cy.get(':nth-child(3) > details > summary > .k-icon').click()
     cy.get(':nth-child(3) > details > .svx-panelbar-item-footer > .svx-button > .k-button').click()
     cy.get(':nth-child(1) > .svx-formfield-content > .k-combobox').find('.k-input-inner').type('Work').wait(3000).type('{enter}')
     cy.get('.svx-panelbar-type-section > :nth-child(2) > .svx-formfield-content > .input-group > .k-textbox').find('.k-input-inner').type('AddAddress1')
     cy.get('.svx-panelbar-type-section > :nth-child(3) > .svx-formfield-content > .input-group > .k-textbox').find('.k-input-inner').type('AddAddress2')
     cy.get('.svx-panelbar-type-section > :nth-child(4) > .svx-formfield-content > .input-group > .k-textbox').find('.k-input-inner').type('AddAddress3')
     cy.get(':nth-child(5) > .svx-formfield-content > .k-combobox').find('.k-input-inner').type('Brazil').wait(5000).type('{enter}')
     cy.get(':nth-child(6) > .svx-formfield-content > .k-combobox').find('.k-input-inner').type('Abu Dhabi').wait(5000).type('{enter}')
     cy.get(':nth-child(3) > details > .svx-panelbar-item-footer > .svx-button > .k-button').click()
     cy.get(':nth-child(2) > .svx-panelbar-type-section > :nth-child(1) > .svx-formfield-content > .k-combobox').find('.k-input-inner').type('Work').wait(3000).type('{enter}')
     cy.get(':nth-child(2) > .svx-panelbar-type-section > :nth-child(2) > .svx-formfield-content > .input-group > .k-textbox').find('.k-input-inner').type('Address11')
     cy.get(':nth-child(2) > .svx-panelbar-type-section > :nth-child(3) > .svx-formfield-content > .input-group > .k-textbox').find('.k-input-inner').type('Address22')
     cy.get(':nth-child(2) > .svx-panelbar-type-section > :nth-child(4) > .svx-formfield-content > .input-group > .k-textbox').find('.k-input-inner').type('Address33')
     cy.get(':nth-child(2) > .svx-panelbar-type-section > :nth-child(5) > .svx-formfield-content > .k-combobox').find('.k-input-inner').type('Bermuda').wait(5000).type('{enter}')
     cy.get(':nth-child(2) > .svx-panelbar-type-section > :nth-child(6) > .svx-formfield-content > .k-combobox').find('.k-input-inner').type('Abeche').wait(5000).type('{enter}')
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').wait(2000).click()
    })
    
it('Addresses -> Edit Address(es)', () => { 
cy.log('1. Expand Address(es) section ')
     cy.get('#tree-item-4_0 > .k-link').click().wait(3000)
     cy.get('[data-col-index="1"] > .k-filtercell > .k-filtercell-wrapper > .k-textbox').find('.k-input-inner').type('EditAddress').wait(5000)
     cy.get('.k-master-row > [data-col-index="1"]').dblclick()
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').click()
     cy.get(':nth-child(3) > details > summary > .k-icon').click()
    
cy.log('2. For one entry, change the category to another one in the list and click SAVE')
     cy.get(':nth-child(1) > .svx-formfield-content > .k-combobox').find('.k-input-inner').eq(0).clear().type('Home').wait(3000).type('{enter}')
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').wait(2000).click()
     cy.get('.svx-column-block-right > .svx-block > .svx-block-body > :nth-child(3) > .k-card > .k-card-body').contains('AddAddress1, AddAddress2, AddAddress3 - Home')

cy.log('3. Click Edit, expand the Address(es) section and change address line 1 of one of the entries. Click SAVE')
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').click()
     cy.get(':nth-child(3) > details > summary > .k-icon').click()
     cy.get('.svx-panelbar-type-section > :nth-child(2) > .svx-formfield-content > .input-group > .k-textbox').find('.k-input-inner').eq(0).clear().type('Add1')
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').wait(2000).click()
     cy.get('.svx-column-block-right > .svx-block > .svx-block-body > :nth-child(3) > .k-card > .k-card-body').contains('Add1, Address22, Address33 - Work')
  
cy.log('4. Click Edit, expand the Address(es) section and change address line 2 of one of the entries. Click SAVE')
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').click()
     cy.get(':nth-child(3) > details > summary > .k-icon').click()
     cy.get('.svx-panelbar-type-section > :nth-child(3) > .svx-formfield-content > .input-group > .k-textbox').find('.k-input-inner').eq(0).clear().type('Add2')
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').wait(2000).click()
     cy.get('.svx-column-block-right > .svx-block > .svx-block-body > :nth-child(3) > .k-card > .k-card-body').contains('Add1, Add2, Address33 - Work')
  
cy.log('5. Click Edit, expand the Address(es) section and change address line 3 of one of the entries. Click SAVE')
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').click()
     cy.get(':nth-child(3) > details > summary > .k-icon').click()
     cy.get('.svx-panelbar-type-section > :nth-child(4) > .svx-formfield-content > .input-group > .k-textbox').find('.k-input-inner').eq(0).clear().type('Add3')
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').wait(2000).click()
     cy.get('.svx-column-block-right > .svx-block > .svx-block-body > :nth-child(3) > .k-card > .k-card-body').contains('Add1, Add2, Add3 - Work')
  
cy.log('6. Click Edit, expand the Address(es) section and change country of one of the entries. Click SAVE')
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').click()
     cy.get(':nth-child(3) > details > summary > .k-icon').click()
     cy.get(':nth-child(5) > .svx-formfield-content > .k-combobox').find('.k-input-inner').eq(0).clear().type('Bhutan').wait(5000).type('{enter}')
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').wait(2000).click()
     cy.get('.svx-column-block-right > .svx-block > .svx-block-body > :nth-child(3) > .k-card > .k-card-body').should('not.contain', 'Bhutan')

cy.log('7. Click Edit, expand the Address(es) section and change/add airport of one of the entries. Click SAVE')
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').click()
     cy.get(':nth-child(3) > details > summary > .k-icon').click()
     cy.get(':nth-child(6) > .svx-formfield-content > .k-combobox').find('.k-input-inner').eq(0).clear().type('Alicante').wait(5000).type('{enter}')
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').wait(2000).click()
     cy.get('.svx-column-block-right > .svx-block > .svx-block-body > :nth-child(3) > .k-card > .k-card-body').should('not.contain', 'Alicante')

cy.log('8. Click Edit, expand the Address(es) section and observe the adjusted fields country and airport')
     cy.get('.modal-buttons > :nth-child(2) > .telerik-blazor').click()
     cy.get(':nth-child(3) > details > summary > .k-icon').click()
     cy.get(':nth-child(5) > .svx-formfield-content > .k-combobox')
     .find('.k-input-inner').invoke('val').then((value) => {expect(value.trim()).to.include('Bhutan')})
     cy.get(':nth-child(6) > .svx-formfield-content > .k-combobox')
     .find('.k-input-inner').invoke('val').then((value) => {expect(value.trim()).to.include('Alicante')})
     cy.get('.modal-buttons > :nth-child(1) > .telerik-blazor').click()

cy.log('cleanup')
     cy.get('#tree-item-4_0 > .k-link').click().wait(3000)
     cy.get('[data-col-index="1"] > .k-filtercell > .k-filtercell-wrapper > .k-textbox').find('.k-input-inner').type('AddAddress').wait(5000)
     cy.get('.k-master-row > [data-col-index="0"] > .k-button > .telerik-blazor').click()
     cy.get('.k-button-solid-primary').click()
    })  
    })